-- AlterTable
ALTER TABLE "Driver" ADD COLUMN     "totalDeliveries" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalEarnings" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "driverPay" DOUBLE PRECISION NOT NULL DEFAULT 15,
ADD COLUMN     "platformProfit" DOUBLE PRECISION NOT NULL DEFAULT 10;
